### ISSUE TITLE
“0xbad0” error code ?

### ISSUE THREAD

**Issue by Yannick-Marietti** [stm32duino/X-NUCLEO-IHM12A1#2]
Hello,

I just made some trials. I put the program inside my small robot with two gear motors (Chinese low quality material, but with a wide range for couple/reduction configuration).
When I run “HelloWord” (thanks for this program !) the “swipe” over the speeds stops and the motors stay frozen on a given running speed.
Looking at Serial output, I get “Warnings ; FLAG Interrupt triggered” end by “Error 0xbad0 detected".
When I cut power of the gear motors, the issue disappear.
 
Looking at the program, it seems to me the issue is coming from over-current.
I did the same trial after removing the “reduction gear” (motors are running freely, without effort) but I get the very same issue.

Can you help me anyway finding the root cause ?

Best regards

**Comment by cparata** [comment]
Hi Yannick,
normally I found this kind of issue when I cut the stabilized power supply to the motors. Cutting the power supply can cause overcurrent issue. If the motors are well powered by a stabilized power supply, I have never experienced this issue. Could you test also the Cube example and see if you see the same issue? Because if I well remember, I had the same behavior also with the Cube firmware and asking for that to motor driver experts, they told me that is normal. Anyway, the IRQ Handler can be customized. You can also try to remove the infinite loop in the callback and see what happens.
Best Regards,
Carlo

**Comment by Yannick-Marietti** [comment]
Thank you Carlo !

I share your answer with M. JEANPIERRE.
I’ll give you a feed-back !

Best regards

Yannick

**Comment by fpistm** [comment]
@Yannick-Marietti 
Some update on this ?

**Comment by Yannick-Marietti** [comment]
Bonsoir Frédéric

Oui, mon collègue Pierre (en copie) s’en occupe.
Dès lors qu’on aura avancé sur ce sujet avec l’enseignant à l’origine de cette issue, je reviendrai vers toi !

Cordialement

Yannick

**Comment by fpistm** [comment]
@Yannick-Marietti 
Ok thanks.
Note: this is on GitHub :wink:

**Comment by fpistm** [comment]
@Yannick-Marietti 
any update on this issue?

**Comment by Yannick-Marietti** [comment]
Bonjour Frédéric,

Non, pas à ma connaissance.

Cordialement

Yannick

________________________________

**Comment by fpistm** [comment]
I close this issue as no feedback since a while.
After some internal discussion, it seems due to a wrong powering of the shield.
